name: SyntheticTimeSeries
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - pip
  - ipython
  - ipykernel
  - pip:
      - matplotlib==3.10.0
      - numpy==2.2.2
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - yfinance==0.2.52